# Generated by Django 5.1.4 on 2025-04-13 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_category_slug_alter_product_category'),
        ('marketplace', '0002_create_default_categories'),
    ]

    operations = [
    ]
