# Generated by Django 5.1.4 on 2025-04-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_product_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('second_hand', 'Second-hand')], default='new', max_length=20),
        ),
    ]
